name: Format and Lint Python code

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        python -m pylint tessellation/ --fail-under=8 --fail-on F --fail-on E

    - name: Run Black
      uses: psf/black@stable
