name: Run tests on Python code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Analysing the code with pylint
      run: |
        python -m pylint tessellation/ --fail-under=8 --fail-on F --fail-on E --fail-on R || pylint-exit $?
        if [ $? -ne 0 ]; then
          echo "An error occurred while running pylint." >&2
          exit 1
        fi
